--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/4/18 18:28:59
-- Server version: 5.7.9
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE football_statistics;

--
-- Definition for table card_statistics_1
--
DROP TABLE IF EXISTS card_statistics_1;
CREATE TABLE card_statistics_1 (
  carduid BIGINT(20) UNSIGNED NOT NULL COMMENT '球员UID',
  ismvp ENUM('0','1') NOT NULL DEFAULT '0' COMMENT '是否是MVP0- 否 1- 是',
  goalnum TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '进球数',
  assists TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '助攻数',
  score TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '评分(需要减小10倍得到真正的评分)',
  yellowcard TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '黄牌数',
  redcard TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '红牌数',
  roomid BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '房间ID'
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 23
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '球员统计';

--
-- Definition for table game_statistics_1
--
DROP TABLE IF EXISTS game_statistics_1;
CREATE TABLE game_statistics_1 (
  roomid BIGINT(20) UNSIGNED NOT NULL COMMENT '比赛房间ID',
  gametype TINYINT(3) UNSIGNED NOT NULL COMMENT '比赛类型',
  ishome ENUM('0','1') NOT NULL DEFAULT '1' COMMENT '是否是主场0- 不是 1- 是',
  ballcontrol TINYINT(3) UNSIGNED NOT NULL COMMENT '控球率',
  shotnum TINYINT(4) NOT NULL DEFAULT 0 COMMENT '总射门次数',
  penaltyshot TINYINT(4) NOT NULL DEFAULT 0 COMMENT '禁区射门次数',
  shotsuccessrate TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '射门成功率',
  passsuccessrate TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '传球成功率',
  freekick TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '任意球',
  corner TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角球',
  saves TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '扑救',
  tacklenum TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '铲球次数',
  foul TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '犯规',
  yellowcard TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '黄牌',
  redcard TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '红牌'
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 23
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
COMMENT = '比赛数据统计';

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;