--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/3/30 20:12:12
-- Server version: 5.7.9
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE playermaxnum;

--
-- Definition for table config
--
DROP TABLE IF EXISTS config;
CREATE TABLE config (
  servernum SMALLINT(5) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (servernum)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '配置表'
ROW_FORMAT = DYNAMIC;

--
-- Definition for table playermaxnum
--
DROP TABLE IF EXISTS playermaxnum;
CREATE TABLE playermaxnum (
  playerNum INT(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (playerNum)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '玩家数量表'
ROW_FORMAT = DYNAMIC;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;