using System.Collections.Generic;
namespace Proto
{
	public class ProtoUtility
	{
		public static int ERROR_OK = 0;
		public static int ERROR_LOGIN = 1;
		public static int ERROR_CREATE = 2;
		public static int ERROR_NEED_LOGIN = 3;
		public static int ERROR_NEED_CREATE = 4;
		public static int ERROR_REPEAT_NAME = 5;
		public static int ERROR_NAME_LENGTH = 6;
		public static int ERROR_ONLINE = 7;
		public static int ERROR_REGISTER = 8;
		public static int ERROR_USERNAME_REGISTERED = 9;
		public static int ERROR_USER_NAME_LENGTH = 10;
		public static int ERROR_USER_PWD_LENGTH = 11;
		public static int ERROR_NAME_HAVED = 12;
		public static int ERROR_NOT_FIND_CARD = 30;
		public static int ERROR_NOT_HAVE_CARD = 31;
		public static int ERROR_FORMATION_CHANGE = 32;
		public static int ERROR_FORMATION_NOTFIND = 33;
		public static int ERROR_USER_LEVEL_FULL = 34;
		public static int ERROR_NOT_FIND_COUNTRY = 35;
		public static int ERROR_UPGRADE_LEVEL_EXPZROE = 36;
		public static int ERROR_CARD_FULL_LEVEL = 37;
		public static int ERROR_CARD_FULL_STAR = 38;
		public static int ERROR_UPGRADE_STAR_MONEYZROE = 39;
		public static int ERROR_UPGRADE_STAR_MATERIAL = 40;
		public static int ERROR_MATERIAL_NOTFIND = 41;
		public static int ERROR_FRAGMENT_NOTFIND = 42;
		public static int ERROR_EQUIP_NOTFIND = 43;
		public static int ERROR_LOOT_LOGIN_REWARD = 44;
		public static int ERROR_LOOTED_LOGIN_REWARD = 45;
		public static int ERROR_ACTIVE_MAP_TIME = 46;
		public static int ERROR_OPEN_MAP = 47;
		public static int ERROR_OPEN_CHILD_MAP = 48;
		public static int ERROR_POWER_NOT_ENOUGH = 49;
		public static int ERROR_CHILD_MAP_LIMIT_USED = 50;
		public static int ERROR_FIGHT = 51;
		public static int ERROR_CARDS_COUNT_LIMIT = 52;
		public static int ERROR_EQUIPS_COUNT_LIMIT = 53;
		public static int ERROR_NOT_HAVE_EQUIP = 54;
		public static int ERROR_EQUIP_FULL_LEVEL = 55;
		public static int ERROR_FREE_SUMMON = 56;
		public static int ERROR_FV_NUMBER = 57;
		public static int ERROR_MONEY_NUMBER = 58;
		public static int ERROR_RMB_NUMBER = 59;
		public static int ERROR_CARD_WORK = 60;
		public static int ERROR_PVP_SELF_FIGHT = 100;
		public static int ERROR_PVP_ENEMY_FIGHT = 101;
		public static int ERROR_PVP_NO_USER = 102;
		public static int ERROR_FRIEND_SELF = 200;
		public static int ERROR_FRIEND_HAD = 201;
		public static int ERROR_FRIEND_NOHAVE = 202;
		public static int ERROR_NOT_FIND_TYPE = 1000;
		public static int ERROR_SERVER = 1001;
		public static int ERROR_LEVEL_NOT_UP = 1002;

		private static bool isInit = false;
		private static Dictionary<int, string> dicDescs = new Dictionary<int, string>();
		public static string getErrorDesc(int nErrorCode)
		{
			if(!isInit)
			{
				dicDescs.Clear();
				dicDescs.Add(ERROR_OK, "成功");
				dicDescs.Add(ERROR_LOGIN, "登录失败");
				dicDescs.Add(ERROR_CREATE, "创建失败");
				dicDescs.Add(ERROR_NEED_LOGIN, "需要登录");
				dicDescs.Add(ERROR_NEED_CREATE, "需要创建");
				dicDescs.Add(ERROR_REPEAT_NAME, "重名");
				dicDescs.Add(ERROR_NAME_LENGTH, "超出长度");
				dicDescs.Add(ERROR_ONLINE, "账号已在线");
				dicDescs.Add(ERROR_REGISTER, "注册失败");
				dicDescs.Add(ERROR_USERNAME_REGISTERED, "用户名已存在");
				dicDescs.Add(ERROR_USER_NAME_LENGTH, "用户名超出长度");
				dicDescs.Add(ERROR_USER_PWD_LENGTH, "密码超出长度");
				dicDescs.Add(ERROR_NAME_HAVED, "昵称已存在");
				dicDescs.Add(ERROR_NOT_FIND_CARD, "没有发现卡牌");
				dicDescs.Add(ERROR_NOT_HAVE_CARD, "您没有这张卡牌");
				dicDescs.Add(ERROR_FORMATION_CHANGE, "替换失败");
				dicDescs.Add(ERROR_FORMATION_NOTFIND, "阵型不存在");
				dicDescs.Add(ERROR_USER_LEVEL_FULL, "玩家已到达最高等级");
				dicDescs.Add(ERROR_NOT_FIND_COUNTRY, "国家不存在");
				dicDescs.Add(ERROR_UPGRADE_LEVEL_EXPZROE, "升级出错(经验为0)");
				dicDescs.Add(ERROR_CARD_FULL_LEVEL, "卡牌到达最高等级");
				dicDescs.Add(ERROR_CARD_FULL_STAR, "卡牌到达最高星级");
				dicDescs.Add(ERROR_UPGRADE_STAR_MONEYZROE, "升星出错(消耗为0)");
				dicDescs.Add(ERROR_UPGRADE_STAR_MATERIAL, "升星出错(材料不足)");
				dicDescs.Add(ERROR_MATERIAL_NOTFIND, "材料不存在");
				dicDescs.Add(ERROR_FRAGMENT_NOTFIND, "碎片不存在");
				dicDescs.Add(ERROR_EQUIP_NOTFIND, "装备不存在");
				dicDescs.Add(ERROR_LOOT_LOGIN_REWARD, "每日登陆奖励拾取失败");
				dicDescs.Add(ERROR_LOOTED_LOGIN_REWARD, "今天已领取过了");
				dicDescs.Add(ERROR_ACTIVE_MAP_TIME, "活动地图未开启");
				dicDescs.Add(ERROR_OPEN_MAP, "大地图为开启");
				dicDescs.Add(ERROR_OPEN_CHILD_MAP, "小地图为开启");
				dicDescs.Add(ERROR_POWER_NOT_ENOUGH, "体力不足");
				dicDescs.Add(ERROR_CHILD_MAP_LIMIT_USED, "今日挑战次数已用完");
				dicDescs.Add(ERROR_FIGHT, "战斗失败");
				dicDescs.Add(ERROR_CARDS_COUNT_LIMIT, "卡牌数量超过上限");
				dicDescs.Add(ERROR_EQUIPS_COUNT_LIMIT, "装备数量超过上限");
				dicDescs.Add(ERROR_NOT_HAVE_EQUIP, "您没有这个装备");
				dicDescs.Add(ERROR_EQUIP_FULL_LEVEL, "装备到达最高等级");
				dicDescs.Add(ERROR_FREE_SUMMON, "免费召唤失败");
				dicDescs.Add(ERROR_FV_NUMBER, "友情点不足");
				dicDescs.Add(ERROR_MONEY_NUMBER, "金币不足");
				dicDescs.Add(ERROR_RMB_NUMBER, "钻石不足");
				dicDescs.Add(ERROR_CARD_WORK, "卡牌出战中");
				dicDescs.Add(ERROR_PVP_SELF_FIGHT, "");
				dicDescs.Add(ERROR_PVP_ENEMY_FIGHT, "");
				dicDescs.Add(ERROR_PVP_NO_USER, "");
				dicDescs.Add(ERROR_FRIEND_SELF, "不能添加自己为好友");
				dicDescs.Add(ERROR_FRIEND_HAD, "好友已存在");
				dicDescs.Add(ERROR_FRIEND_NOHAVE, "好友不存在");
				dicDescs.Add(ERROR_NOT_FIND_TYPE, "系统错误");
				dicDescs.Add(ERROR_SERVER, "系统错误");
				dicDescs.Add(ERROR_LEVEL_NOT_UP, "系统错误");
			}
			string outStr;
			dicDescs.TryGetValue(nErrorCode, out outStr);
			return outStr;
		}


		public static int USER_DATA_FIRST_USERID = 0;
		public static int USER_DATA_FIRST_PROPERTY = 1;
		public static int USER_DATA_FIRST_CARDS = 2;
		public static int USER_DATA_FIRST_EQUIPS = 3;
		public static int USER_DATA_FIRST_MATERIALS = 4;
		public static int USER_DATA_FIRST_FRAGMENTS = 5;
		public static int USER_DATA_FIRST_FORMATION = 6;
		public static int USER_DATA_FIRST_LIMIT = 7;
		public static int USER_DATA_FIRST_MAPS = 8;
		public static int USER_DATA_FIRST_CREATETIME = 9;
		public static int USER_DATA_FIRST_LASTLOGIN = 10;
		public static int USER_DATA_FIRST_LASTLEAVE = 11;
		public static int USER_DATA_CARDS_UID = 0;
		public static int USER_DATA_CARDS_CID = 1;
		public static int USER_DATA_CARDS_USERID = 2;
		public static int USER_DATA_EQUIPS_UID = 1;
		public static int USER_DATA_EQUIPS_ID = 2;
		public static int USER_DATA_EQUIPS_LEVEL = 3;
		public static int USER_DATA_EQUIPS_EXP = 4;
		public static int USER_DATA_EQUIPS_CARDUID = 5;
		public static int USER_DATA_FRAGMENTS_ID = 1;
		public static int USER_DATA_FRAGMENTS_NUMBER = 2;
		public static int USER_DATA_MATERIALS_ID = 1;
		public static int USER_DATA_MATERIALS_NUMBER = 2;
		public static int USER_DATA_PROPERTY_NONE = 0;
		public static int USER_DATA_PROPERTY_USERID = 1;
		public static int USER_DATA_PROPERTY_NICK = 2;
		public static int USER_DATA_PROPERTY_LEVEL = 3;
		public static int USER_DATA_PROPERTY_EXP = 4;
		public static int USER_DATA_PROPERTY_MONEY = 5;
		public static int USER_DATA_PROPERTY_RMB = 6;
		public static int USER_DATA_PROPERTY_RMBGM = 7;
		public static int USER_DATA_PROPERTY_FORMATION = 8;
		public static int USER_DATA_PROPERTY_CLUP = 9;
		public static int USER_DATA_PROPERTY_COUNTRY = 10;
		public static int USER_DATA_PROPERTY_LEADER = 11;
		public static int USER_DATA_PROPERTY_CARDSCOUNT = 12;
		public static int USER_DATA_PROPERTY_EQUIPSCOUNT = 13;
		public static int USER_DATA_PROPERTY_FRIENDSHIP = 14;
		public static int USER_DATA_PROPERTY_POWERCUR = 15;
		public static int USER_DATA_PROPERTY_POWERALL = 16;
		public static int USER_DATA_PROPERTY_POWRETIME = 17;
		public static int USER_DATA_PROPERTY_PVPCUR = 18;
		public static int USER_DATA_PROPERTY_PVPALL = 19;
		public static int USER_DATA_PROPERTY_PVPRETIME = 20;
		public static int USER_DATA_PROPERTY_HONOR = 21;
		public static int USER_DATA_PROPERTY_FVSUMMONTIME = 22;
		public static int USER_DATA_PROPERTY_MONEYSUMMONTIME = 23;
		public static int USER_DATA_PROPERTY_RMBSUMMONTIME = 24;
		public static int USER_DATA_PROPERTY_MEDICALCUR = 25;
		public static int USER_DATA_PROPERTY_MORALECUR = 26;
		public static int USER_DATA_LIMIT_LOGINREWARDID = 1;
		public static int USER_DATA_LIMIT_LOGINREWARDDAY = 2;
		public static int USER_DATA_LIMIT_LOGINREWARDLOOT = 3;
		public static int EQUIP_TYPE_POSITION = 1;
		public static int EQUIP_TYPE_CLOTH = 2;
		public static int EQUIP_TYPE_COUNTRY = 3;
		public static int EQUIP_TYPE_CLUB = 4;
		public static int MAP_TYPE_COMMON = 1;
		public static int MAP_TYPE_ELITE = 2;
		public static int MAP_TYPE_ACTIVE = 3;
		public static int CHILD_MAP_TYPE_COMMON = 1;
		public static int CHILD_MAP_TYPE_LIMITNUMBER = 2;
		public static int CLUB_JERSEY_USERID = 0;
		public static int CLUB_TEAM_SIGN_USERID = 0;
		public static int CLUB_TROPHY_USERID = 0;
		public static int CLUB_INFO_USERID = 0;
		public static int SERVER_OPERATION_NTF_PROPERTY_CHANGE = 1;
		public static int SERVER_OPERATION_NTF_CARD_CHANGE = 2;
		public static int SERVER_OPERATION_NTF_CARD_DELETE = 3;
		public static int SERVER_OPERATION_NTF_CARD_ADD = 4;
		public static int SERVER_OPERATION_NTF_EQUIP_ADD = 5;
		public static int SERVER_OPERATION_NTF_EQUIP_DELETE = 6;
		public static int SERVER_OPERATION_NTF_EQUIP_CHANGE = 7;
		public static int SERVER_OPERATION_NTF_FRAGMENT_OPER = 8;
		public static int SERVER_OPERATION_NTF_MATERIAL_OPER = 9;
		public static int SERVER_OPERATION_NTF_FORMATION_OPER = 10;
		public static int SERVER_OPERATION_NTF_DIRTYTIMES = 20;
		public static int SUMMON_TYPE_FV = 1;
		public static int SUMMON_TYPE_MONEY = 2;
		public static int SUMMON_TYPE_RMB = 3;
		public static int SUMMON_TYPE_RMBTEN = 4;
		public static int CARD_QUALITY_TYPE_WHITE = 1;
		public static int CARD_QUALITY_TYPE_GREEN = 2;
		public static int CARD_QUALITY_TYPE_BLUE = 3;
		public static int CARD_QUALITY_TYPE_PURPLE = 4;
		public static int CARD_QUALITY_TYPE_ORANGE = 5;
		public static int CARD_QUALITY_TYPE_RED = 6;
		public static int PVP_POSITION_NONE = 0;
		public static int PVP_POSITION_ATTACK = 1;
		public static int PVP_POSITION_DEFENSE = 2;
		public static int MYSQL_MAX_NUM = 2000000;
		public static int MEM_MAX_NUM = 200000;
		public static int ID_LIST_MAX_NUM = 2000;
		public static int REDPOINT_PVPFIGHT = 0;
		public static int TACTICS_TYPE_TEAMMEMTALITY = 1;
		public static int TACTICS_TYPE_PASSDIRECTION = 2;
		public static int TACTICS_TYPE_ATTACKDIRECTION = 3;
		public static int TACTICS_TYPE_DEFENSE = 4;
		public static int TACTICS_TYPE_COMPRESSION = 5;
		public static int TACTICS_TYPE_TACKLE = 6;
		public static int TACTICS_TYPE_OFFSIDE = 7;
		public static int TACTICS_TYPE_MARKING = 8;


		public static int CSID_LOGIN_REQ = 1;
		public static int SCID_LOGIN_ACK = 2;
		public static int CSID_CREATE_REQ = 3;
		public static int SCID_CREATE_ACK = 4;
		public static int CSID_GETINFO_REQ = 5;
		public static int SCID_GETINFO_ACK = 6;
		public static int CSID_REGISTER_REQ = 7;
		public static int SCID_REGISTER_ACK = 8;
		public static int CSID_UPGRADELEVEL_REQ = 100;
		public static int SCID_UPGRADELEVEL_ACK = 101;
		public static int CSID_UPGRADESTAR_REQ = 102;
		public static int SCID_UPGRADESTAR_ACK = 103;
		public static int CSID_LOOTLOGINREWARD_REQ = 104;
		public static int SCID_LOOTLOGINREWARD_ACK = 105;
		public static int CSID_PVE_REQ = 200;
		public static int SCID_PVE_ACK = 201;
		public static int CSID_SELLCARDS_REQ = 202;
		public static int SCID_SELLCARDS_ACK = 203;
		public static int CSID_POSITIONCHANGE_REQ = 204;
		public static int SCID_POSITIONCHANGE_ACK = 205;
		public static int CSID_UPGRADEEQUIPLEVEL_REQ = 206;
		public static int SCID_UPGRADEEQUIPLEVEL_ACK = 207;
		public static int CSID_EQUIPWORD_REQ = 208;
		public static int SCID_EQUIPWORD_ACK = 209;
		public static int CSID_EQUIPREST_REQ = 210;
		public static int SCID_EQUIPREST_ACK = 211;
		public static int CSID_SELLEQUIPS_REQ = 212;
		public static int SCID_SELLEQUIPS_ACK = 213;
		public static int CSID_SUMMON_REQ = 214;
		public static int SCID_SUMMON_ACK = 215;
		public static int CSID_GETDIRTYTIME_REQ = 300;
		public static int SCID_GETDIRTYTIME_ACK = 301;
		public static int CSID_APPLYGAME_REQ = 400;
		public static int SCID_APPLYGAME_ACK = 401;
		public static int CSID_GETPLAYERINFO_REQ = 402;
		public static int SCID_GETPLAYERINFO_ACK = 403;
		public static int CSID_GET_SUMMARY_REQ = 404;
		public static int SCID_GET_SUMMARY_ACK = 405;
		public static int CSID_FootballerInfo_REQ = 500;
		public static int SCID_FootballerInfo_ACK = 501;
		public static int CSID_FootballerADD_REQ = 502;
		public static int SCID_FootballerADD_ACK = 503;
		public static int CSID_FootballerDestory_REQ = 504;
		public static int SCID_FootballerDestory_ACK = 505;
		public static int CSID_FormationInfo_REQ = 510;
		public static int SCID_FormationInfo_ACK = 511;
		public static int CSID_FormationSet_REQ = 512;
		public static int SCID_FormationSet_ACK = 513;
		public static int CSID_Property_REQ = 600;
		public static int SCID_Property_ACK = 601;
		public static int CSID_Chat_REQ = 700;
		public static int SCID_Chat_ACK = 701;
		public static int CSID_ChatSetInfo_REQ = 702;
		public static int SCID_ChatSetInfo_ACK = 703;
		public static int CSID_Friend_REQ = 800;
		public static int SCID_Friend_ACK = 801;
		public static int CSID_FriendADD_REQ = 802;
		public static int SCID_FriendADD_ACK = 803;
		public static int CSID_FriendDestory_REQ = 804;
		public static int SCID_FriendDestory_ACK = 805;
		public static int CSID_FriendFind_REQ = 806;
		public static int SCID_FriendFind_ACK = 807;
		public static int CSID_TACTICSGET_REQ = 900;
		public static int SCID_TACTICSGET_ACK = 901;
		public static int CSID_TACTICSSET_REQ = 902;
		public static int SCID_TACTICSSET_ACK = 903;
		public static int CSID_CREATECLUB_REQ = 1000;
		public static int SCID_CREATECLUB_ACK = 1001;
		public static int CSID_UPDATECLUB_REQ = 1002;
		public static int SCID_UPDATECLUB_ACK = 1003;
		public static int CSID_GETCLUBINFO_REQ = 1004;
		public static int SCID_GETCLUBINFO_ACK = 1005;
		public static int CSID_CLUBSHIRT_REQ = 1010;
		public static int SCID_CLUBSHIRT_ACK = 1011;
		public static int CSID_UPDATECLUBSHIRT_REQ = 1012;
		public static int SCID_UPDATECLUBSHIRT_ACK = 1013;
		public static int CSID_CLUBTEAMSIGN_REQ = 1020;
		public static int SCID_CLUBTEAMSIGN_ACK = 1021;
		public static int CSID_UPDATECLUBTEAMSIGN_REQ = 1022;
		public static int SCID_UPDATECLUBTEAMSIGN_ACK = 1023;
		public static int CSID_GETTROPHYLIST_REQ = 1030;
		public static int SCID_GETTROPHYLIST_ACK = 1031;
		public static int CSID_ADDTROPHY_REQ = 1032;
		public static int SCID_ADDTROPHY_ACK = 1033;
		public static int CSID_REDPOINT_REQ = 2000;
		public static int SCID_REDPOINT_ACK = 2001;
		public static int CSID_LEAGUERANK_REQ = 2010;
		public static int SCID_LEAGUE_RANK_ACK = 2011;
		public static int SCID_LEAGUE_RANK_NTF = 2012;
		public static int CSID_LEAGUE_SCHEDULE_REQ = 2013;
		public static int SCID_LEAGUE_SCHEDULE_ACK = 2014;
		public static int SCID_LEAGUE_SCHEDULE_NTF = 2015;
		public static int CSID_LEAGUE_FOOTBALLER_RANK_REQ = 2016;
		public static int SCID_LEAGUE_FOOTBALLER_RANK_ACK = 2017;
		public static int SCID_LEAGUE_FOOTBALLER_RANK_NTF = 2018;
		public static int SCID_USER_DATA_NTF = 1009;
		public static int CSID_HeartBeat_REQ = 9999;
	}
}